language: jvm
os: linux
dist: trusty
jdk: openjdk8
script:
  - "./gradlew build -xtest"
services:
  - docker
after_success:
  - docker build -t $REPO/$IMAGE_NAME .
  - echo "$TOKEN" | docker login  docker.pkg.github.com --username b1412 --password-stdin
  - docker tag $REPO/$IMAGE_NAME:latest $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
  - docker push $REPO/$IMAGE_NAME:latest
  - docker push $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
env:
  global:
    - IMAGE_NAME=kotlin-gateway
    - REPO=docker.pkg.github.com/b1412/kotlin-gateway