language: jvm
os: linux
dist: trusty
jdk: openjdk8

services:
- docker
script:
- ./gradlew build
- docker build -t $IMAGE_NAME .
- docker login docker.pkg.github.com -u b1412 -p $TOKEN
- docker tag $IMAGE_NAME:latest docker.pkg.github.com/b1412/docker-mysql/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
- docker push docker.pkg.github.com/b1412/docker-mysql/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
env:
  global:
    - IMAGE_NAME=kotlin-eureka